### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by ghost** [andreapavoni/ttfm_bot#1]
Hi. Nice to see a bot written to run from an exe. there's an error in the README.md re env variables:

`TTFM_ADMIN_MAIN_ID`: the ID of the user that will be the first and main admin

should read `TTFM_MAIN_ADMIN_ID`  apparently and throws error, so was easy to fix.

Run on win10. Seems to work nicely with super minimal overhead. gr8 solution for small rooms / on demand rooms xx cheers.

**Comment by andreapavoni** [comment]
hi @SgtWhack!

first of all, thank you for the kind words and for submitting this issue :-) I've fixed the typo in README so that others won't incur in the same problem.

on a side note, I've only did testing on Linux (on a raspberry pi, currently running in `Disco Clubbing` room) and on macOS. I've built `exe`s for WIndows because Golang has cross-compiling features but I didn't have access to any Windows to effectively run the bot.

In theory, it might work well in big rooms too, but I still haven't had the chance to try (except joining crowded rooms as non-moderator to snag songs and populate some playlists).

The only feature I didn't tried is dj-queue moderation, because I never had too much people who wanted to dj.

Thank you again for the issue, I'm open to feature-requests, if any.
